spring:
  application:
    name: service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=verify-full&sslrootcert=${DB_CERTIFICAT_PATH}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      schema: ${DB_SCHEMA}
  flyway:
    fail-on-missing-locations: true
    table: schema_version
    locations: classpath:db/migration
    default-schema: ${DB_SCHEMA:public}
  ai:
    mistralai:
      api-key: ${MISTRALAI_API_KEY}
      chat:
        options:
          model: mistral-medium

app:
  front:
    url: ${FRONT_URL}
  email:
    brevo:
      api-key: ${BREVO_API_KEY}
  access_token:
    secret: lPYjkhqrgGSDgLdSSzvbvRDR6p5ihzlo0izKNJ3UCsI
    expiration: 8
  refresh_token:
    secret: sVlrNcMQZnixrI6gcwW9H73JFfsE/QTt08TcxAE+S5yXWV5phcIQ9s/mQ4SAeMGs6ooEi/+Urk0WTIiMS8WJ8Q==
    expiration: 12
  cors:
    allowed-origins: ${FRONT_URL:https://app.legipilot.com, http://app.legipilot.com}

aws:
  s3:
    endpoint: ${S3_ENDPOINT:https://s3.fr-par.scw.cloud}
    accesskey: ${S3_ACCESS_KEY}
    secretkey: ${S3_SECRET_KEY}
    bucketname: legipilot-documents
    environnement: prod