spring:
  application:
    name: service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:legipilotdb}
    username: ${DB_USER:service}
    password: ${DB_PASSWORD:password}
    hikari:
      schema: ${DB_SCHEMA:public}
  flyway:
    fail-on-missing-locations: true
    table: schema_version
    locations: classpath:db/migration
    default-schema: ${DB_SCHEMA:public}
  ai:
#    openai:
#      api-key: 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
#      chat:
#        options:
#          model: gpt-4.1-mini
    mistralai:
      api-key: iwhSuCbAy0psU8ggMn2iuXdL6gsOsFPZ
      chat:
        options:
          model: mistral-medium

app:
  front:
    url: http://localhost:3000
  email:
    brevo:
      api-key: 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
  access_token:
    secret: lPYjkhqrgGSDgLdSSzvbvRDR6p5ihzlo0izKNJ3UCsI
    expiration: 8
  refresh_token:
    secret: sVlrNcMQZnixrI6gcwW9H73JFfsE/QTt08TcxAE+S5yXWV5phcIQ9s/mQ4SAeMGs6ooEi/+Urk0WTIiMS8WJ8Q==
    expiration: 12
  cors:
    allowed-origins: ${FRONT_URL:https://localhost:3000, http://localhost:3000}

aws:
  s3:
    endpoint: ${S3_ENDPOINT:http://localhost:9000}
    accesskey: ${S3_ACCESS_KEY:service}
    secretkey: ${S3_SECRET_KEY:password}
    #    endpoint: ${S3_ENDPOINT:https://s3.fr-par.scw.cloud}
    #    accesskey: ${S3_ACCESS_KEY:SCWZ99RRNRXH9KDS272P}
    #    secretkey: ${S3_SECRET_KEY:2d285781-b9d6-4b8c-9c6f-0ab4911f5853}
    bucketname: legipilot-documents
    environnement: dev