package com.legipilot.service.core.administrator;

import com.legipilot.service.core.administrator.domain.model.*;
import com.legipilot.service.core.administrator.authentication.domain.Authentication;
import com.legipilot.service.core.collaborator.domain.model.*;
import com.legipilot.service.core.company.domain.model.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

public class AdministratorFixtures {

    public static final Administrator GABIN_BLOQUET = Administrator.builder()
            .email("gabin.bloquet.pro@gmail.com")
            .authentication(Authentication.builder()
                    .tenant(Tenant.GOOGLE)
                    .sub("01839743847822")
                    .build())
            .password(new EncodedPassword("1encodedPassword$"))
            .firstname("Gabin")
            .lastname("Bloquet")
            .picture(Optional.of("https://lh3.googleusercontent.com/a/ACg8ocJKWyOxBluEKgndVlPfP-eMEnfieQgx_aYbDeDOoxshS8qPNbI=s96-c"))
            .fonction(Fonction.DIRIGEANT)
            .phone("0762699316")
            .roles(List.of(Role.ADMIN))
            .state(AccountState.NOT_VALIDATED)
            .build();

    public static final Collaborator GABIN_COLLABORATOR_INITIALISE = Collaborator.builder()
            .firstname("Gabin")
            .lastname("Bloquet")
            .picture(Optional.of("https://lh3.googleusercontent.com/a/ACg8ocJKWyOxBluEKgndVlPfP-eMEnfieQgx_aYbDeDOoxshS8qPNbI=s96-c"))
            .status(Status.ACTIVE)
            .contactDetails(ContactDetails.builder()
                    .professionalEmail("gabin.bloquet.pro@gmail.com")
                    .professionalPhone("0762699316")
                    .build())
            .personalSituation(PersonalSituation.builder()
                    .drivingLicenses(List.of())
                    .build())
            .documents(List.of())
            .notes(List.of())
            .build();

    public static final Collaborator JULIE_LACROIX_INITIALISE = Collaborator.builder()
            .firstname("Julie")
            .lastname("Lacroix")
            .birthDate(LocalDate.of(1990, 2, 17))
            .birthPlace("Lille")
            .nationality("Française")
            .civility(Civility.Madame)
            .socialSecurityNumber(new SocialSecurityNumber("2 90 02 59 123 456 78"))
            .picture(Optional.of("https://legipilot-documents.s3.fr-par.scw.cloud/public/prod/visuals/julie.jpg"))
            .status(Status.ACTIVE)
            .contactDetails(ContactDetails.builder()
                    .personalPhone("06 12 23 34 45")
                    .personalEmail("julie.lacroix@gmail.com")
                    .personalAddress("15 rue des Lilas, 59000 Lille")
                    .emergencyContact(EmergencyContact.builder()
                            .civility(Civility.Monsieur)
                            .firstname("Maxime")
                            .lastname("Lacroix")
                            .phone("06 54 43 32 21")
                            .email("maxime.lacroix@gmail.com")
                            .build())
                    .professionalPhone("07 21 32 43 54")
                    .professionalEmail("julie.lacroix@entreprise.fr")
                    .iban("FR76 1111 2222 3333 4444 5555 666")
                    .build())
            .personalSituation(PersonalSituation.builder()
                    .maritalStatus("Marié(e)")
                    .numberOfChildren(2)
                    .educationLevel("BAC+2")
                    .drivingLicenses(List.of("B"))
                    .rqth(false)
                    .build())
            .professionalSituation(ProfessionalSituation.builder()
                    .jobTitle("Chargée d'accueil")
                    .contractType(ContractType.CDI)
                    .hireDate(LocalDate.of(2018, 3, 5))
                    .workHoursPerWeek(35)
                    .workHoursType(WorkHoursType.HEURES)
                    .location("Lille")
                    .responsible("Benoit Durant")
                    .build())
            .contractInformations(ContractInformations.builder()
                    .category(SocioProfessionalCategory.EMPLOYE)
                    .classification("Position 2, Coefficient 250")
                    .annualSalary(BigDecimal.valueOf(32000))
                    .variableCompensation(BigDecimal.valueOf(1000))
                    .benefitsInKind(BigDecimal.valueOf(1200))
                    .totalCompensation(BigDecimal.valueOf(34200))
                    .trialPeriod("2 mois")
                    .nonCompeteClause(false)
                    .stayType("APS")
                    .stayNumber("123456789")
                    .stayValidityDate(LocalDate.parse(String.valueOf(LocalDate.of(1990, 2, 17))))
                    .build())
            .documents(List.of())
            .notes(List.of())
            .build();

    public static final Collaborator GABIN_COLLABORATOR = Collaborator.builder()
            .firstname("Gabin")
            .lastname("Bloquet")
            .picture(Optional.of("https://lh3.googleusercontent.com/a/ACg8ocJKWyOxBluEKgndVlPfP-eMEnfieQgx_aYbDeDOoxshS8qPNbI=s96-c"))
            .status(Status.ACTIVE)
            .contactDetails(ContactDetails.builder()
                    .professionalEmail("gabin.bloquet.pro@gmail.com")
                    .professionalPhone("0762699316")
                    .build())
            .personalSituation(PersonalSituation.builder()
                    .drivingLicenses(List.of())
                    .build())
            .documents(List.of())
            .notes(List.of())
            .build();

    public static final Collaborator JULIE_LACROIX = Collaborator.builder()
            .firstname("Julie")
            .lastname("Lacroix")
            .birthDate(LocalDate.of(1990, 2, 17))
            .birthPlace("Lille")
            .nationality("Française")
            .civility(Civility.Madame)
            .socialSecurityNumber(new SocialSecurityNumber("2 90 02 59 123 456 78"))
            .picture(Optional.of("https://legipilot-documents.s3.fr-par.scw.cloud/public/prod/visuals/julie.jpg"))
            .status(Status.ACTIVE)
            .contactDetails(ContactDetails.builder()
                    .personalPhone("06 12 23 34 45")
                    .personalEmail("julie.lacroix@gmail.com")
                    .personalAddress("15 rue des Lilas, 59000 Lille")
                    .emergencyContact(EmergencyContact.builder()
                            .civility(Civility.Monsieur)
                            .firstname("Maxime")
                            .lastname("Lacroix")
                            .phone("06 54 43 32 21")
                            .email("maxime.lacroix@gmail.com")
                            .build())
                    .professionalPhone("07 21 32 43 54")
                    .professionalEmail("julie.lacroix@entreprise.fr")
                    .iban("FR76 1111 2222 3333 4444 5555 666")
                    .build())
            .personalSituation(PersonalSituation.builder()
                    .maritalStatus("Marié(e)")
                    .numberOfChildren(2)
                    .educationLevel("BAC+2")
                    .drivingLicenses(List.of("B"))
                    .rqth(false)
                    .build())
            .professionalSituation(ProfessionalSituation.builder()
                    .jobTitle("Chargée d'accueil")
                    .contractType(ContractType.CDI)
                    .hireDate(LocalDate.of(2018, 3, 5))
                    .workHoursPerWeek(35)
                    .workHoursType(WorkHoursType.HEURES)
                    .location("Lille")
                    .responsible("Benoit Durant")
                    .build())
            .contractInformations(ContractInformations.builder()
                    .category(SocioProfessionalCategory.EMPLOYE)
                    .classification("Position 2, Coefficient 250")
                    .annualSalary(BigDecimal.valueOf(32000))
                    .variableCompensation(BigDecimal.valueOf(1000))
                    .benefitsInKind(BigDecimal.valueOf(1200))
                    .totalCompensation(BigDecimal.valueOf(34200))
                    .trialPeriod("2 mois")
                    .nonCompeteClause(false)
                    .stayType("APS")
                    .stayNumber("123456789")
                    .stayValidityDate(LocalDate.parse(String.valueOf(LocalDate.of(1990, 2, 17))))
                    .build())
            .documents(List.of())
            .notes(List.of())
            .build();

    public static final Company JUSTIANA = Company.builder()
            .name("Justiana")
            .siren(new Siren("944797877"))
            .siret(new Siret("94479787700015"))
            .legalForm("SASU")
            .nafCode(new NafCode("62.01Z"))
            .activityDomain("Programmation, conseil et autres activités informatiques")
            .collectiveAgreement(new CollectiveAgreement("1486", "Convention collective nationale des bureaux d'études techniques"))
            .administrators(List.of(GABIN_BLOQUET))
            .collaborators(List.of(GABIN_COLLABORATOR_INITIALISE, JULIE_LACROIX_INITIALISE))
            .picture(Optional.empty())
            .build();

    public static final Company JUSTIANA_AVEC_INFOS = Company.builder()
            .name("Justiana")
            .siren(new Siren("944797877"))
            .siret(new Siret("94479787700015"))
            .legalForm("SASU")
            .nafCode(new NafCode("62.01Z"))
            .activityDomain("Programmation, conseil et autres activités informatiques")
            .collectiveAgreement(new CollectiveAgreement("1486", "Convention collective nationale des bureaux d'études techniques"))
            .administrators(List.of(GABIN_BLOQUET))
            .collaborators(List.of(GABIN_COLLABORATOR, JULIE_LACROIX))
            .picture(Optional.empty())
            .build();

    public static final Administrator GABIN_WITH_JUSTIANA = Administrator.builder()
            .email("gabin.bloquet.pro@gmail.com")
            .authentication(Authentication.builder()
                    .tenant(Tenant.GOOGLE)
                    .sub("01839743847822")
                    .build())
            .password(new EncodedPassword("1encodedPassword$"))
            .firstname("Gabin")
            .lastname("Bloquet")
            .picture(Optional.of("https://lh3.googleusercontent.com/a/ACg8ocJKWyOxBluEKgndVlPfP-eMEnfieQgx_aYbDeDOoxshS8qPNbI=s96-c"))
            .phone("0762699316")
            .fonction(Fonction.DIRIGEANT)
            .roles(List.of(Role.ADMIN))
            .companies(List.of(JUSTIANA))
            .state(AccountState.NOT_VALIDATED)
            .build();
}
