export const INITIAL_CREATION_STATE = {
    id: undefined,
    firstname: "",
    lastname: "",
    civility: undefined,
    birthDate: undefined,
    birthPlace: undefined,
    nationality: undefined,
    socialSecurityNumber: undefined,
    status: "ACTIVE",

    jobTitle: undefined,
    contractType: undefined,
    hireDate: undefined,
    endDate: undefined,
    location: undefined,
    responsible: undefined,
    workHoursPerWeek: undefined,

    category: undefined,
    classification: undefined,
    annualSalary: undefined,
    variableCompensation: undefined,
    totalCompensation: undefined,
    benefitsInKind: undefined,
    trialPeriod: undefined,
    nonCompeteClause: false,

    personalEmail: "",
    personalPhone: undefined,
    personalAddress: undefined,
    emergencyCivility: undefined,
    emergencyFirstname: undefined,
    emergencyLastname: undefined,
    emergencyPhone: undefined,
    emergencyEmail: undefined,
    professionalEmail: undefined,
    professionalPhone: undefined,

    maritalStatus: undefined,
    numberOfChildren: undefined,
    educationLevel: undefined,
    drivingLicenses: undefined,
    rqth: undefined,
    picture: undefined,
}